= Anypoint Runtime Fabric でのインバウンドトラフィックの有効化
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Fabric は、Mule アプリケーションや API プロキシへのインバウンドトラフィックを管理するための負荷分散を提供します。ネットワークトラフィックは、アプリケーションの複数のレプリカで分散されます。デフォルトでは、レプリカは異なるワーカー VM にデプロイされます。

Runtime Fabric は、複数の環境で共有できます。インストール後、各 Runtime Fabric の 1 つ以上の環境を設定して、アプリケーションデプロイメントを有効にします。Mule アプリケーションや API ゲートウェイをデプロイできるようにするには、1 つ以上の環境を各 Runtime Fabric に関連付ける必要があります。

本番環境にデプロイされるアプリケーションは、本番以外のアプリケーションから分離された Runtime Fabric のインスタンスにデプロイされる必要があります。

[NOTE]
デフォルトでは、不要なリソースをコンシュームしないようにインバウンドトラフィックが無効になっています。Mule アプリケーションや API ゲートウェイでインバウンド接続をリスンできるようにするには、インバウンドトラフィックを有効にします。インバウンドトラフィックはデフォルトで無効になっているため、Mule アプリケーションや API ゲートウェイでインバウンド要求を受信できるようにするには、手動で有効にする必要があります。


インバウンドトラフィックを有効にする前に、有効な TLS 証明書を提供する必要があります。証明書にはパスフレーズが必要です。また、証明書は Runtime Fabric にデプロイされている各アプリケーションのドメインを指定する共通名 (CN) を使用して設定されている必要があります。

* 共通名にワイルドカードが含まれている場合、デプロイされている各アプリケーションのエンドポイントの形式は `{app-name}.{common-name}` のようになります。
* 共通名にワイルドカードが含まれていない場合、エンドポイントの形式は `{common-name}/{app-name}` のようになります。

== 外部ロードバランサの要件

各コントローラ VM は、内部ロードバランサのレプリカを実行し、ポート 443 でリスンするように設定されています。複数のコントローラ VM を実行する場合、各コントローラ VM に直面する Runtime Fabric 外に外部ロードバランサが必要になります。外部ロードバランサでは、TCP 負荷分散がサポートされている必要があります。ロードバランサは、各コントローラ VM の IP アドレスが含まれるサーバプールを使用して設定されている必要があります。また、外部ロードバランサには、ポート 443 をリスンする状態チェックもセットアップされている必要があります。

この外部ロードバランサの設定では、次のことを実現できます。

* 高可用性を維持する
* 障害から保護する
* 内部ロードバランサのレプリカが再起動するか、削除されて別のコントローラ VM で再スケジュールされた場合に、自動フェイルオーバーを適切に処理する

[NOTE]
コントローラ VM は、Anypoint Runtime Fabric を強化するコンポーネントを実行する専用の仮想マシンです。

Anypoint Runtime Fabric へのすべてのインバウンドトラフィックは、TLS を使用して暗号化されます。次の手順では、インバウンドトラフィックを有効にするために TLS 証明書を設定および使用する方法について説明します。有効になると、Runtime Fabric に送信される HTTP 要求は、301 応答を受信して、ポート 443 で HTTPS にリダイレクトします。

== 必要なロールと権限を割り当てる

. Runtime Fabric で実行されるアプリケーションを使用する環境を決定します。
. 必要な権限があることを確認します。
+
取得した権限が伝播されるまで最大 5 分ほどかかることがあります。

.. Anypoint Platform から、*[Access Management (アクセス管理)]* をクリックします。
+
[Access Management (アクセス管理)] にアクセスできない場合、システム管理者にアクセス権を要求します。

.. *[Users (ユーザ)]* をクリックします。
.. ユーザ名がある行を見つけ、青いリンクをクリックします。
.. *[Runtime Manager]* タブで、Runtime Fabric 環境の *[Manage Runtime Fabrics (Runtime Fabric の管理)]* 権限を有効にします。

.. *[Secrets Manager (シークレットマネージャ)]* タブで、Runtime Fabric 環境の *[Manage Secret Groups (シークレットグループの管理)]*、*[Write Secrets (シークレットの作成)]*、*[Read Secrets Metadata (シークレットメタデータの読み取り)]* 権限を有効にします。

== 証明書とキーのペアを生成する

Runtime Fabric の内部ロードバランサの証明書とキーのペアが必要になります。ペアがすでにある場合、両方のファイルの種類が .pem で、キーストアにパスコードがあり、共通名が Runtime Fabric で使用するドメインと一致している必要があります。ペアがない場合、評価のために次の手順を実行して生成します。

. マシンで次のコマンドを実行して証明書とキーのペアを生成します。
+
----
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
----

. キーのパスフレーズを入力します。
. 必要な情報 (国や都道府県など) を入力します。共通名を求められた場合、Runtime Fabric で使用するドメインを入力します。

共通名にワイルドカード (*.example.com など) を使用する場合、アプリケーション URL では `{app-name}.example.com` の形式が使用されます。使用しない場合、アプリケーション URL では `example.com/{app-name}` の形式が使用されます。


== TLS コンテキストを作成する

次の手順に従って、証明書とキーのペアを TLS コンテキストに含めるには、それをシークレットマネージャに保存します。これは、後で Runtime Fabric へのインバウンドトラフィックを暗号化するために使用されます。

. Anypoint Platform ホームページからシークレットマネージャに移動します。
+
[NOTE]
適切なビジネスグループに属していることを確認し、左側のサイドバーで Runtime Fabric 環境を選択します。

. *[Create Secret Group (シークレットグループを作成)]* ボタンをクリックします。
. *[General (一般)]* で、シークレットグループの名前を入力します。
. *[Save (保存)]* をクリックします。
. 左側のサイドバーで *[Keystore (キーストア)]* をクリックし、キーストアを作成します。
.. *[Add Keystore (キーストアを追加)]* ボタンをクリックします。
+
*[Add Keystore (キーストアを追加)]* ボタンが表示されない場合、シークレットグループが編集モードで表示されていることを確認します。*[Secret Groups (シークレットグループ)]* に戻り、グループの横にある *[Edit (編集)]* をクリックします。

.. キーストアの名前を入力します。
+
キーストアを以下の TLS コンテキストに追加するときに、この名前でキーストアが識別されます。

.. *[Certificate File (証明書ファイル)]* で、*[Choose File (ファイルを選択)]* を選択し、`.pem` 証明書ファイルを選択します。
.. *[Key File (キーファイル)]* で、*[Choose File (ファイルを選択)]* を選択し、`.pem` キーファイルを選択します。
.. キーパスフレーズを入力します。
.. 必要に応じて、CA パスが含まれる個別の証明書ファイルをアップロードします。
.. *[Save (保存)]* をクリックします。
+
[NOTE]
不明なエラーが発生した場合、証明書ファイルに CA パスが含まれていることが原因である可能性があります。続行する前に、CA パスを独自のファイルに移動して個別にアップロードします。

. *[TLS Context (TLS コンテキスト)]* をクリックし、次の手順を実行します。
+
[NOTE]
*[Add TLS Context (TLS コンテキストを追加)]* が表示されない場合、シークレットグループが編集モードで表示されていることを確認します。*[Secret Groups (シークレットグループ)]* ページに戻り、グループの横にある *[Edit (編集)]* をクリックします。

.. TLS コンテキストの名前を入力します。後で Runtime Fabric に適用するときに、この名前で TLS コンテキストが識別されます。
.. デフォルトの TLS バージョン (TLS 1.2) を使用します。
.. *[Target (対象)]* で、*[Anypoint Security]* を選択します。これにより、TLS コンテキストが設定され、Runtime Fabric に適用できるようになります。
.. *[Keystore (キーストア)]* で、以前に設定したキーストアの名前を選択します。
.. *[Save (保存)]* をクリックします。

. TLS コンテキストを保存したら、*[Secret Groups (シークレットグループ)]* をクリックし、*[Finish (完了)]* をクリックします。これにより、*Runtime Fabric* の TLS コンテキストが有効になります。

== インバウンドトラフィックを有効にする

TLS コンテキストを作成したら、TLS コンテキストを Runtime Fabric に適用して、セキュアな受信トラフィックを有効にします。

. [Runtime Manager] に移動し、*[Runtime Fabric]* をクリックします。
. Runtime Fabric の名前をクリックして、管理ページを開きます。
. *[Associated Environments (関連付けられた環境)]* タブで、Runtime Fabric 環境が Runtime Fabric に関連付けられていることを確認します。
. *[Inbound Traffic (インバウンドトラフィック)]* タブを選択し、[Enable inbound traffic (インバウンドトラフィックを有効化)] 切り替えをオンにします。
. *[Basic Configuration (基本設定)]* をクリックし、次の手順を実行します。
.. 内部ロードバランサで実行するレプリカの数を設定します。
+
[NOTE]
本番環境では、2 つ以上のレプリカが必要です。これらのレプリカは、コントローラ VM でのみ実行されます。

.. 内部ロードバランサの各レプリカに割り当てる CPU やメモリの量を決定します。
+
[NOTE]
TLS の終了は、計算コストが高くなります。より多くの CPU を割り当てるほど、スループットが向上し、遅延が減少します。

. [TLS Configuration (TLS 設定)] で、次の手順を実行します。
.. *[Environment (環境)]* メニューから、Runtime Fabric 環境を選択します。
.. *[Secrets Group (シークレットグループ)]* メニューから、以前に作成した TLS コンテキストが含まれるシークレットグループを選択します。
+
[NOTE]
シークレットグループが表示されない場合、「*Manage Runtime Fabrics (Runtime Fabric の管理)*」権限がアカウントに割り当てられていることを確認します。

.. *[TLS Context (TLS コンテキスト)]* メニューから、Runtime Fabric で使用される TLS コンテキストを選択します。


. *[Deploy (デプロイ)]* をクリックして内部ロードバランサをデプロイします。成功すると、ページの右下にメッセージが表示されます。デプロイメントには、最大 1 分ほどかかることがあります。デプロイメントの状況は、フォームの上部で確認できます。状況が *[Applied (適用済み)]* に移行すると、内部ロードバランサが正常にデプロイされ、インバウンドトラフィックが有効になります。

== インバウンドトラフィックが有効になっていることの確認

Runtime Fabric にデプロイされているアプリケーションの共通名 (CN) を解決するには、CN を外部ロードバランサまたは各コントローラ VM の IP アドレスにマップするように DNS を設定する必要があります。DNS を設定する前にアプリケーションのインバウンドトラフィックをテストするには、ドメインに設定されている IP アドレスとホストヘッダーを使用して要求をアプリケーションに送信します。

ドメインの構造は、証明書の CN７ でワイルドカードが使用されているかどうかによって異なります。次に例を示します。

* ワイルドカードが含まれる CN (*.example.com など) では、`Host: {app-name}.example.com` という要求ヘッダー形式が使用されます。次の cURL コマンドを使用して、検証します。
+
----
curl -Lvk -XGET https://{ip-address}/{path} -H 'Host: {app-name}.example.com'
----

* ワイルドカードが含まれない CN (example.com など) では、`Host: example.com` という要求ヘッダー形式が使用されます。次の cURL コマンドを使用して、検証します。
+
----
curl -Lvk -XGET https://{ip-address}/{app-name}/{path} -H 'Host: example.com'`
----

== トラフィックを有効にした後

Runtime Fabric は、有効になっている各アプリケーションに受信トラフィックをルーティングするように設定されている必要があります。クライアントからデプロイ済み
アプリケーションに要求を送信するには、次の操作を実行します。

* Runtime Fabric の各コントローラ VM で HTTPS トラフィックを負荷分散するように外部ロードバランサを設定する。
* 外部ロードバランサを追加するときに下記の詳細オプションを確認する。
* TLS 証明書から取得される共通名を使用する前に DNS を設定する。DNS は、Runtime Fabric にデプロイされている
アプリケーションや API ゲートウェイに要求を送信するために必要になります。共通名を外部ロードバランサまたはコントローラ VM の
IP アドレスにマップするために「A レコード」を DNS プロバイダに追加する必要があります。

新しいアプリケーションをデプロイする場合や、Runtime Fabric の既存のアプリケーションを管理する場合、[Ingress (イングレス)] タブが有効になります。 
このタブでは、インバウンドトラフィックを許可すべきかどうかを指定できます。インバウンドトラフィックを有効にすると、
デフォルトの動作は新しいアプリケーションデプロイメントを許可するように切り替わります。インバウンドトラフィックを有効にする前に
Runtime Fabric にデプロイされたアプリケーションがある場合、この設定が有効になるまでそれらはインバウンド要求を受信しません。

== 追加の設定オプション

次の表では、環境で設定することが必要になる場合がある追加の設定オプションについて説明します。この場合、
​*「Source IP (送信元 IP)」*​は要求を行っているクライアントを指します。

[%header%autowidth.spread,cols="a,a"]
|===
|値 |説明
| *Max connections (最大接続数)*
| 最大許容同時接続数。

*デフォルト値*: 512 接続

| *Max requests per connection (接続あたりの最大要求数)*
| 接続あたりの最大許容要求数。 +
この値により、接続でどれぐらいの再利用が許可されるのかが決まります。この値を低くする場合、TLS で暗号化された接続を終了および再確立するのに必要な CPU の量を考慮してください。

*最大許容値*: 接続あたり 1000 要求

*デフォルト値*: 1000

| *Connection idle time-out (接続アイドルタイムアウト)*
| アイドル接続を許可する最大時間。 +
この値は、アイドル接続を終了してリソースを解放するのに役立ちます。 +
この値は、常に *[read request time-out (読み取り要求タイムアウト)]* よりも高くする必要があります。

*デフォルト値*: 15 秒

| *Read request time-out (読み取り要求タイムアウト)*
| 要求の読み取りに費やすことができる最大時間。この時間を超えると終了します。+
この値により、大きなペイロードの要求を行ったり、低速なクライアントを終了してリソースを使用できる状態を維持したりできます。+
これは、応答の送信後に接続を終了しないクライアントや低速な要求によって接続プールが枯渇することを回避するのに役立ちます。

Mule アプリケーションの応答時間がこの値よりも長くなると、接続が自動的に終了します。 +
この値は、常に上記で設定される *[connection idle time-out (接続アイドルタイムアウト)]* よりも低くする必要があります。

*デフォルト値*: 10 秒

| *Max pipeline depth (最大パイプライン深度)*
| 同じクライアントからの最大許容要求数。 +
この値は、クライアントが送信できる同時要求数を定義します。 +
クライアントがこの数値を超えると、キューの要求が応答を受信するまで超過要求が読み取られなくなります。

*デフォルト値*: クライアントあたり 10 要求

| *[Source IP header name (送信元 IP ヘッダー名)]* と *[enable proxy protocol (プロキシプロトコルを有効化)]* 
| Runtime Fabric がロードバランサの背後にある場合、これらの設定を行います。

ここで設定する値は、シナリオによって異なります。

. Runtime Fabric がロードバランサの背後にない。 +
Runtime Fabric がロードバランサの背後にデプロイされていない場合、これらの値は設定しないでください。
+
*Source IP header name (送信元 IP ヘッダー名)*: 空白 +
*Enable proxy protocol (プロキシプロトコルを有効化)*: オフ
. Runtime Fabric がプロキシプロトコルが設定された AWS ロードバランサの背後にある。 +
 Runtime Fabric がプロキシプロトコルが有効になっている AWS ロードバランサの背後にデプロイされている場合、*[enable proxy protocol (プロキシプロトコルを有効化)]* オプションをオンにする必要があります。
+
*Source IP header name (送信元 IP ヘッダー名)*: 空白 +
*Enable proxy protocol (プロキシプロトコルを有効化)*: オン
. Runtime Fabric が AWS 以外のロードバランサの背後にある。 +
 Runtime Fabric が別の種別のロードバランサ (F5 や nginx など) の背後にデプロイされている場合、送信元 IP ヘッダー名を入力する必要があります。2 つの一般的な送信元 IP ヘッダーを次に示します。
+
* Forwarded: RFC7239 準拠の IP ヘッダー。
* X-Forwarded-For: ロードバランサの 1 つ以上の IP (「192.16.23.34、172.16.21.36」など) が含まれる 2014 年以前の非標準ヘッダー
+
*Source IP header name (送信元 IP ヘッダー名)*: 空白以外 +
*Enable proxy protocol (プロキシプロトコルを有効化)*: オフ

*デフォルト値*: 空白とオフ。

|=== 

== 内部ロードバランサのログ

内部ロードバランサのログレベルを定義できます。Runtime Fabric では、次のログレベル (詳細度の昇順で記載) がサポートされています。

* FATAL
* ERROR
* WARNING
* INFO
* VERBOSE
* Debug (デバッグ)
* TRACE

ログレベルが詳細になるほど (WARNING から TRACE)、各要求でコンシュームする CPU リソースが増えます。ログレベルを調整したり、内部ロードバランサのリソースを割り当てたりする場合、この点を考慮してください。

デフォルトでは、エンドポイントの背後にあるすべての IP アドレスのアクティビティが記録されます。より詳細なログレベルを使用する場合、CPU 消費量を減らすには、IP 検索条件を追加して特定の IP アドレスのみを記録します。また、この機能を使用して、特定の IP アドレスまたは限られた数の IP アドレスの接続をデバッグすると、ログの数量が減少します。

=== 内部ロードバランサのログを設定する

. Anypoint Platform から [Runtime Manager] を選択します。
. *[Runtime Fabric]* をクリックします。
. *[Inbound Traffic (インバウンドトラフィック)]* タブから、[Logs + (ログ +)] リンクをクリックします。
. *[Add Filter (検索条件を追加)]* をクリックします。
. *[IP]* 項目で、CIDR 表記を使用して 1 つの IP アドレスまたはアドレスのサブセットを入力します。
. この IP 検索条件に適用するログレベルを選択します。
. *[OK]* をクリックします。

== 関連情報

* xref:deploy-resource-allocation.adoc[Anypoint Runtime Fabric でのリソース割り当ての決定]
* xref:deploy-to-runtime-fabric.adoc[Anypoint Runtime Fabric への Mule アプリケーションのデプロイ]
