= Runtime Fabric からのノードの追加または削除

Runtime Fabric では、Runtime Fabric にノードを追加したり、Runtime Fabric からノードを削除したりできます。ノードの追加または削除が必要になる場合があるシナリオを以下に示します。

* ノードを追加して Runtime Fabric をスケールアップする。
* ノードを削除または追加して、Runtime Fabric の健全性と安定性を確保する。
* ノードを削除し、OS パッチを実行した後、ノードを Runtime Fabric に再度追加する。

== Runtime Fabric へのノードの追加

ノードを追加する前に、新しいノードのインフラストラクチャをプロビジョニングします。クラスタに参加できるようにするには、新しいノードが Runtime Fabric インストールと同じネットワーク上に存在する必要があります。

. 新しいノードの仮想マシンで `/opt/anypoint/runtimefabric` ディレクトリを作成します。
+
----
mkdir -p /opt/anypoint/runtimefabric
----

. `init.sh` インストールスクリプトを新しいノードの `/opt/anypoint/runtimefabric` ディレクトリの下にコピーします。
+
このスクリプトは、Runtime Fabric のインストール時にダウンロードしたファイルに含まれます。

. 環境ファイルを既存のノードの `/opt/anypoint/runtimefabric` ディレクトリから新しいノードの同じディレクトリにコピーします。
+
環境ファイルを正しいノード種別 (コントローラまたはワーカー) からコピーしたことを確認します。

. コピーした環境ファイル内で次の環境変数を変更します。
+
* RTF_PRIVATE_IP
* RTF_DOCKER_DEVICE
* RTF_ETCD_DEVICE (コントローラノードのみ)
* RTF_ACTIVATION_DATA が存在する場合は削除する
* RTF_INSTALL_ROLE=joiner

. 新しいノードで特権ユーザとして `init.sh` スクリプトを実行します。このスクリプトを実行する場合、実行可能権限の追加が必要になる場合があります。
+
----
sudo chmod +x ./init.sh
----
+
このスクリプトにより、新しいノードが Runtime Fabric クラスタに参加します。

. 新しいノードが Runtime Fabric に追加されたことを確認します。
+
----
sudo gravity status
----

== Runtime Fabric からのノードの削除

Runtime Fabric クラスタからノードを削除するには、次のコマンドを実行します。

----
sudo gravity leave
----

このコマンドは、ノードで実行されているすべての Runtime Fabric サービスをシャットダウンします。また、すべてのソフトウェアとデータが削除されます。

成功した場合、このコマンドは、開始された削除操作の ID を出力します。次のコマンドを使用して、このコマンドの進行状況を監視できます。

----
gravity status
----

`sudo gravity leave` を使用してノードを削除できない場合、`--force` オプションを使用してコマンドを再度実行することが必要になる場合があります。次のコマンドを実行して、ノードをリモートで削除することもできます。

----
sudo gravity remove <node-name>
----

`<node>` は、削除するノードを示します。これには、ノードに割り当てられたホスト名またはその IP アドレスのいずれかを指定できます。
