= Runtime Fabric にデプロイされたアプリケーションの監視

Runtime Fabric にデプロイされたアプリケーションと API ゲートウェイには、Anypoint Platform 内のメトリクスを表示できる Anypoint Monitoring のネイティブサポートが含まれます。

== Anypoint Monitoring

xref:monitoring::index.adoc[Anypoint Monitoring] には、アプリケーションネットワークの Mule フローとコンポーネントからのフィードバックを提供するツールがあります。Runtime Fabric にデプロイされたアプリケーションと API ゲートウェイでは、Anypoint Monitoring はすべての顧客に基本的なメトリクスを提供します。Titanium ユーザは、アプリケーションログの取得や検索などの追加機能にアクセスできます。

Runtime Fabric にアプリケーションをデプロイすると、デフォルトで Anypoint Monitoring が有効になります。Anypoint Monitoring を無効にするには、アプリケーションをデプロイするときに次のカスタムプロパティを渡します。

----
anypoint.platform.config.analytics.agent.enabled=false
----

=== メトリクス

各 Mule アプリケーションと API ゲートウェイのレプリカは、メトリクスデータを収集して Anypoint Monitoring に送信するメトリクスエージェントを実行します。各レプリカは最大 100 メガバイトのメトリクスをキャッシュできます。その後、最新のデータ用のストレージを提供するためにメトリクスのローテーションが開始されます。メトリクスを Anypoint Monitoring に送信できない場合、通常はレプリカごとに少なくとも 4 日分のストレージが提供されます。カスタムメトリクスの使用では、より多くのストレージがコンシュームされる場合があります。

=== ログ (Titanium)

各 Mule アプリケーションと API ゲートウェイのレプリカは、最大 450 メガバイトのログデータをディスクに保存できます。その後ログデータをローテーションし、最新のログデータのストレージを提供します。

Mule アプリケーションと API ゲートウェイの各レプリカによって生成されたログが収集され、それらが実行されているワーカーノードのディスクに書き込まれます。各ワーカーノードは 1 つのログ転送エージェントを実行します。そのエージェントがこの場所を監視し、ログデータを Anypoint Monitoring に送信します。

[NOTE]
ログ転送エージェントは、1 秒あたり最大 300 キロバイトのログデータを送信できます。ワーカーノードごとにデプロイするレプリカは 50 個以内にしてください。

== Anypoint Visualizer

xref:visualizer::index.adoc[Anypoint Visualizer] には、アプリケーションネットワークグラフのさまざまな側面のビューが表示されます。グラフを使用してアプリケーションネットワークを調査し、問題を特定して、決定を下すことができます。

[WARNING]
デフォルトでは、アプリケーションを Mule Runtime 4.x にデプロイすると、Anypoint Visualizer は無効になります。詳細は、xref:visualizer::setup.adoc#enable-header-injection[「ヘッダー挿入の有効化」]を参照してください。

