= Runtime Fabric でのセキュアプロパティの管理
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

セキュアプロパティは、Runtime Fabric クラスタのローカルに追加され、安全に保存され、環境ごとにスコープ設定されます。セキュアプロパティには、スコープ設定された環境にカスタムプロパティとしてデプロイされた Mule アプリケーションから暗号化されていない形式でアクセスできます。

== rtfctl のインストール 

Runtime Fabric のセキュアプロパティをローカルで管理するには、rtftl ツールが必要です。セキュアプロパティの管理に進む前に、xref:install-rtfctl.adoc[rtfctl をインストール]する手順に従います。

== セキュアプロパティを設定する

. `rtfctl` がインストールされているコントローラーノードにログインします。 
. 次のコマンドのプレースホルダ項目を置き換えて実行し、特定の環境で Runtime Fabric にセキュアプロパティを設定します。
+
----
rtfctl apply secure-property --key <my_key> --value <my_value> -n <environment_id>
----
+
* *<my_key>*: Mule アプリケーションで値を参照するために使用されるセキュアプロパティのキー。
* *<my_value>*: 保存するセキュアプロパティの値。
* *<environment_id>*: このセキュアプロパティをスコープ設定する Anypoint 環境 ID。この環境にデプロイされたアプリケーションのみがこのセキュアプロパティにアクセスできます。

== セキュアプロパティを表示する

. `rtfctl` がインストールされているコントローラーノードにログインします。 
. 次のコマンドのプレースホルダ項目を置き換えて実行し、特定の環境で Runtime Fabric に適用されるセキュアプロパティを表示します。
+
----
rtfctl get secure-properties -n <environment_id>
----
+
* *<environment_id>*: セキュアプロパティを表示する Anypoint 環境 ID。

== 関連情報

* xref:install-rtfctl.adoc[rtfctl のインストール]
* xref:manage-proxy.adoc[Runtime Fabric で使用されるプロキシの管理]
