= Runtime Fabric のバックアップと復元
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== 前提条件

バックアップまたは復元操作を実行する前に、Runtime Fabric がインストールまたはアップグレードされていることを
https://docs.mulesoft.com/release-notes/runtime-fabric/runtime-fabric-installer-release-notes[インストーラバージョン 1.1.1561762676, role=external, window=_blank] 以降を使用して確認します。 
インストーラバージョンを確認するには、Runtime Fabric ノードで `gravity status` を実行します。

万一システム障害が発生してもアプリケーションが保持されるように、Runtime Fabric が自動的にバックアップされるようにします。 
1 時間ごとのバックアップを設定することを強くお勧めします。Runtime Fabric の外部にある外部ストレージにバックアップ
アーカイブを保存します。

== バックアップを作成する

バックアップを作成するには、クラスタ内の任意のコントローラノードで (ルートアクセス権を持つ) 特権ユーザとして次のコマンドを実行します。

----
gravity backup /var/lib/gravity/planet/share/backup.tar.gz
----

次の省略可能なパラメータを `gravity backup` コマンドに渡すことができます。

* `--follow`: バックアップジョブのログをターミナルに出力します。
* `--timeout`: バックアップジョブの期限を指定します (例: 30 秒、5 分など)。デフォルトは 20 分です。
* `--log-file`: ログをファイルに出力します。

このコマンドにより、現在のシステム状態のアーカイブが `/var/lib/gravity/planet/share/backup.tar.gz` に作成されます。 

== システムを復元する

バックアップからシステムを復元するには、既存の Runtime Fabric クラスタを使用するか、復元するクラスタと
同じハードウェア (サーバ、ディスクの数など) が含まれる新しい Runtime Fabric クラスタを作成します。

[WARNING]
Runtime Fabric クラスタの新しいバージョンで Runtime Fabric を復元することはできません。新しいインストールでは、
バックアップと同じバージョンの Runtime Fabric インストールバンドルを使用する必要があります。

. Runtime Fabric のコントローラノードに (ルートアクセス権を持つ) 特権ユーザとしてログインします。

. 圧縮されたバックアップアーカイブファイルを、復元する環境の任意のノードのフォルダに移動します。 
このファイルは次のコマンドを使用して安全に転送できます。
+
----
scp /backup-path/to-restore.tar.gz your_username@remotehost:/var/lib/gravity/planet/share
----

. バックアップアーカイブからクラスタを復元します。
+
----
sudo gravity restore /var/lib/gravity/planet/share/to-restore.tar.gz
----

次の省略可能なパラメータを渡すことができます。

* `--follow`: バックアップジョブのログを stdout に出力します。
* `--timeout`: バックアップジョブの期限を指定します (例: 30 秒、5 分など)。デフォルトは 20 分です。
* `--log-file`: ログをファイルに出力します。

このプロセスには数分かかります。 

== 関連情報

* xref:manage-nodes.adoc[Runtime Fabric からのノードの追加または削除]
* xref:install-sys-reqs.adoc[Anypoint Runtime Fabric のシステム要件]
