= Runtime Fabric で使用されるプロキシの管理
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

インターネットへの Runtime Fabric アウトバウンド接続で使用されるプロキシ設定を更新します。これには、Anypoint コントロールプレーンに接続するための HTTP プロキシ、およびメトリクスとログを Anypoint Monitoring に送信するための SOCKS5 プロキシが含まれます。

== rtfctl のインストール 

Runtime Fabric のプロキシ設定を管理するには、rtftl ツールが必要です。プロキシの設定に進む前に、xref:install-rtfctl.adoc[rtfctl をインストール]する手順に従います。

== 監視プロキシを更新する

. `rtfctl` がインストールされているコントローラーノードにログインします。 
. 次のコマンドを実行し、プレースホルダの値を次の値に置き換えます。
+
----
rtfctl apply monitoring-proxy "socks5://<user>:<pass>@<10.0.0.2>:<8080>"
----
+
* *<user>*: SOCKS5 プロキシの認証に必要なユーザ名。
* *<pass>*: SOCKS5 プロキシの認証に必要なパスワード。 +
[NOTE]
パスワードは URL にエンコードされている必要があります。
* *<10.0.0.2>*: SOCKS5 プロキシへのアクセスに使用される IP アドレスまたはホスト名。
* *<8080>*: SOCKS5 プロキシが要求をリスンするホストのポート。
. 変更が成功したことを確認するには、次のコマンドを実行して、監視プロキシの現在の値を出力します。 +
`rtfctl get monitoring-proxy`

出力は期待される値と一致する必要があります。

== HTTP プロキシを更新する

この操作には 2 つの手順が必要です。 

* Runtime Fabric の各ノードでスクリプトを実行してクラスタを更新する。
* Runtime Fabric 内で実行されているサービスにプロキシの値を適用する。

=== 各ノードでスクリプトを実行する

. `/opt/anypoint/runtimefabric/scripts/` にある Runtime Fabric のインストールに使用されたコントローラノードから、`set_dockerd_proxy.sh` を同じ場所 (`/opt/anypoint/runtimefabric/scripts/`) にある各コントローラノードとワーカーノードにコピーします。 +
[NOTE]
このスクリプトが見つからない場合は、サポートチケットを開いてください。
. `/opt/anypoint/runtimefabric/env` ファイルを更新して `RTF_HTTP_PROXY` および `RTF_NO_PROXY` 変数の値を設定します。 + 
`RTF_HTTP_PROXY` 値には、インラインの認証値を使用します。例: `http://user:Password@1.1.1.1:80` +
`RTF_NO_PROXY` 値には、プロキシを通過しないホストのカンマ区切りのリストを使用します。例: `1.1.1.1,no-proxy.com`
. スクリプト `/opt/anypoint/runtimefabric/scripts/set_dockerd_proxy.sh` を実行します。
. 各コントローラノードとワーカーノードでこれらの手順を繰り返したら、これらのプロキシ値を Runtime Fabric 内で実行されているサービスに適用します。

=== Runtime Fabric サービスにプロキシ値を適用する

. `rtfctl` がインストールされているコントローラーノードにログインします。 
. 次のコマンドを実行し、プレースホルダの値を次の値に置き換えます。
+
----
rtfctl apply http-proxy "http://<user>:<pass>@<10.0.0.1>:<8080>" --no-proxy "<1.1.1.1:8888,2.2.2.2.:9999>"
----
+
* *<user>*: HTTP プロキシの認証に必要なユーザ名。
* *<pass>*: HTTP プロキシの認証に必要なパスワード。 +
[NOTE]
パスワードは URL にエンコードされている必要があります。
* *<10.0.0.1>*: HTTP プロキシにアクセスするための IP アドレスまたはホスト名。
* *<8080>*: HTTP プロキシが要求をリスンするホストのポート。
* *<1.1.1.1:8888,2.2.2.2.:9999>*: カンマで区切られた `NO_PROXY` ホストとポート。
. 変更が成功したことを確認するには、次のコマンドを実行して、HTTP プロキシの現在の値を出力します。`rtfctl get http-proxy`

出力は期待される値と一致する必要があります。

== 関連情報

* xref:install-port-reqs.adoc[Anypoint Runtime Fabric のネットワークとポートの要件]
