= Runtime Fabric でのログの表示および設定
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Fabric では、以下に関する情報を提供するログファイルが生成されます。

* デプロイされた Mule アプリケーション
* デプロイされた API プロキシ
* Runtime Fabric サービス
* Kubernetes サービス

== ログレベル

Runtime Fabric では、ログファイルに書き込まれるメッセージの重要度のレベルを指定できます。

[%header,cols="3*a"]
|===
| 値
| 説明
| コマンド

| すべての優先度
| すべてのメッセージをリストします。
| なし

| ERROR
| 例外が発生した場合のエラーメッセージのみをリストします。
| priority:ERROR

| FATAL
| アプリケーションが失敗した場合の致命的なメッセージのみをリストします。
| priority:FATAL

| INFO
| 有益情報のメッセージをリストします。
| priority:INFO

| SYSTEM
| アプリケーションとワーカーのスタートアップに関するメッセージをリストします。
| priority:SYSTEM

| CONSOLE
| オブジェクトストアの設定など、コンソールイベントに関するメッセージをリストします。
| priority:CONSOLE

| WARN
| 警告メッセージをリストします。
| priority:WARN

| Debug (デバッグ)
| デバッグメッセージをリストします。
| priority:DEBUG
|===

ログレベルは、デプロイ中に Mule アプリケーションまたは API プロキシごとに指定します。




[WARNING]
ログレベルは、Mule アプリケーションまたは API プロキシのデプロイ時に指定します。デプロイ後にログレベルを変更することはできません。


== ログの表示

Runtime Fabric で実行されているアプリケーションとサービスから出力されたログのストリームはオペレーションセンターに表示されます。ページの左にある [Logging (ログ)] に移動すると、ログインターフェースが表示されます。

=== アプリケーションからのログの表示

オペレーションセンターを使用すると、デプロイされたアプリケーションからのログを表示できます。ログ転送がセットアップされていない場合、これが役立つ可能性があります。

. オペレーションセンターの左サイドバーで [Kubernetes] をクリックします。
. [Pods (ポッド)] タブをクリックします。
. 検索入力の近くの右ドロップダウンで、アプリケーションがデプロイされた環境 ID を選択します。
. 対象のアプリケーションの名前で始まるポッド名を見つけます。
. ポッド名をクリックして [Logs (ログ)] を選択します。

対象のアプリケーションに検索条件が適用された [Logs (ログ)] タブにページがリダイレクトされます。

[NOTE]
最新のログを表示するには、ページの右上にある [Refresh (更新)] ボタンをクリックします。

=== 絞り込み

ログをドリルダウンして表示するのに役立つ 2 つの絞り込みレベルがあります。

* _Containers (コンテナ)_: コンテナの名前に基づいて絞り込みを行います。
* _Pods (ポッド)_: ポッドの名前に基づいて絞り込みを行います。これは、アプリケーション名の後にワイルドカード (`%`) を続けて指定する場合に役立ちます。


== 外部サービスへのログの転送

Anypoint Runtime Fabric では、アプリケーションとクラスタのログを外部のログサービスに転送できます。Runtime Fabric に組み込まれているログ転送機能を使用すると、ログデータを TCP または UDP 経由で rsyslog サーバに送信できます。

Anypoint Runtime Fabric コンポーネントと Mule アプリケーションからのログデータを外部のログソリューションに転送し、表示、保持、およびアラート処理を一元的に行うことができます。Runtime Fabric に含まれる `rsyslog` クライアントサービスでは、TCP または UDP 経由での rsyslog サーバへのログ転送トランスミッションが提供されます。Splunk や Logstash などのログサービスでは、rysslog クライアントからログデータを受信するためのメソッドが提供されます。

Anypoint Runtime Fabric では、ダッシュボードが提供され、パフォーマンスや可用性が低下した場合に重要なメトリクスに関するアラートが表示されます。これらは、オペレーションセンターを使用して表示および調整できます。アラートを受信するには、SMTP サーバが必要です。


=== 手順

. ターミナルを使用して、コントローラ VM へのシェル/SSH 接続を開きます。
. `log-forwarder.yaml` という名前のファイルを作成します。
. 以下の表に基づいてカスタマイズした後、このファイルに次の内容を追加します。
+
----
kind: logforwarder
version: v2
metadata:
   name: log-forwarder
spec:
   address: 192.168.100.1:514
   protocol: udp
----
+
環境に固有の次の値を使用します。
+
[%header,cols="2*a"]
|===
|キー | 説明
|`name` | ログ転送ルールの名前を指定します。
|`address` | ログデータを転送するエンドポイントとポートを指定します。
|`protocol` | データの送信先のプロトコルを指定します。サポートされるプロトコルは TCP または UDP です。
|===
+
. コントローラ VM で次のコマンドを実行し、以前に作成したファイルを参照します。
----
gravity resource create log-forwarder.yaml
----

これで、ログは外部のログサービスに転送されます。

== 関連情報

* xref:configure-alerting.adoc[Anypoint Runtime Fabric でのアラートの設定]
* xref:deploy-to-runtime-fabric.adoc[Runtime Fabric に Mule アプリケーションをデプロイする]
