= Anypoint Runtime Fabric でのオペレーションセンターの使用
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

このトピックでは、Anypoint Runtime Fabric 内で組み込みのオペレーションセンターを使用して、ダッシュボードの監視、ログの表示、デバッグ情報のダウンロードを行う方法について説明します。

== オペレーションセンターへのアクセス

Runtime Fabric のインストールプロセス中に、ログへの最新の出力の 1 つに、オペレーションセンターへのログインに必要な次の情報が含まれます。

----
Administrator access:
URL:      https://<any-node-ip>:32009/web
User:     admin@runtime-fabric
Password: ***********************
----

この情報は、インストーラ VM のログ出力から取得します。

. ターミナルを使用して、インストーラ VM へのシェル/SSH 接続を開きます。
. 次のコマンドを使用してログファイルを開き、ログイン情報を検索します。
+
----
cat /var/log/rtf-init.log | grep -B 1 -A 3 "Administrator access"
----
+
. 詳細を安全な場所に保存します。
. Web ブラウザを開き、該当の URL に移動します (`<any-node-ip>` は、任意のコントローラ VM の公開または非公開 IP アドレスで置き換えます)。
. ログから取得したログイン情報を使用して、Runtime Fabric のオペレーションセンターにログインします。

[NOTE]
ポート 32009 が開いており、セキュリティグループ、ネットワークセキュリティグループ、またはファイアウォールルール内でそのポートにアクセスできることを確認します。非公開 IP アドレスを使用する場合、VM が存在しているネットワークと同じ内部ネットワークにアクセスできることを確認します。

== ダッシュボードの表示

オペレーションセンターにログインしたら、ページの左にタブのリストが表示されます。[Monitoring (監視)] に移動すると、表示可能なダッシュボードが表示されます。

=== アプリケーションからのメトリクスの表示

オペレーションセンターを使用すると、デプロイされたアプリケーションからのメトリクスを表示できます。

. オペレーションセンターの左サイドバーで [Kubernetes] をクリックします。
. [Pods (ポッド)] タブをクリックします。
. 検索入力の近くの右ドロップダウンで、アプリケーションがデプロイされた環境 ID を選択します。
. 対象のアプリケーションの名前で始まるポッド名を見つけます。
. ポッド名をクリックして [Monitoring (監視)] を選択します。

対象のアプリケーションに検索条件が適用された [Monitoring (監視)] タブにページがリダイレクトされます。デフォルトでは、CPU、メモリ、ネットワーク、およびファイルシステムの使用量を示す一連のグラフが表示されます。


=== クラスタとポッド

ダッシュボードは 2 つの主なカテゴリに分割されます。

* _[Cluster (クラスタ)]_ には、Runtime Fabric クラスタ全体のメトリクスが表示されます。検索条件には `nodename` が含まれており、これを使用して、特定の VM で絞り込むことができます。
* _[Pods (ポッド)]_ には、Runtime Fabric クラスタ内で実行されている各サービスのメトリクスが表示されます。検索条件には `namespace` と `podname` が含まれており、これを使用して、監視する特定のサービスを指定できます。
** `namespace` を選択すると、アプリケーションがデプロイされている Anypoint 環境 ID に対応する GUID が表示されます。
** `podname` を選択すると、アプリケーション名のプレフィックスが付けられた値が表示されます。これは、各アプリケーションデプロイメントのレプリカを参照します。

== ログの表示

xref:runtime-fabric-logs.adoc[「Runtime Fabric でのログの表示および設定」]を参照してください。

== デバッグ情報のダウンロード

Runtime Fabric の問題が発生した場合、MuleSoft サポートチームが、デバッグ情報を含むパッケージ化ファイルを要求することがあります。以下の手順に従って、デバッグ情報パッケージを生成してください。

. オペレーションセンターで、ページの左側にある [Admin (管理)] リンクをクリックします。
. ページの右上にある [Download Debug Info (デバッグ情報をダウンロード)] ボタンをクリックします。
+
* Runtime Fabric が要求を処理している間、新しいタブが開く場合があります。このファイルの生成には数分かかることがあります。
+
. `report.tar.gz` という名前のファイルのダウンロードが開始されます。

== 関連情報

* xref:configure-alerting.adoc[Anypoint Runtime Fabric でのアラートの設定]
* xref:runtime-fabric-logs.adoc[Anypoint Runtime Fabric でのログ転送の設定]
